project_id = "qmzovsnnsuqcckzumima"

[auth]
enabled = true
site_url = "https://tarteb-805.netlify.app"
additional_redirect_urls = [
  "https://tarteb-805.netlify.app",
  "https://tarteb-805.netlify.app/auth/callback",
  "http://localhost:3000",
  "http://localhost:3000/auth/callback"
]

[auth.external.google]
enabled = true
client_id = "2853621329-5b73b1it8slebgt5e9io945l5g6v417u.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false
email_optional = false
